### PR TITLE
Implemented recognition of wheel straight #8 and #11

### PR DESCRIPTION
**Pull request by Naktibalda**

### CODE REVIEW

**Comment by rafanoronha** [comment]
Thanks and welcome aboard!

**Comment by Naktibalda** [comment]
Hi,

My objectives in this project are:
1. Contribute
2. Learn Scala
3. Learn Git

End result is not really important to me, as I have no use for poker
server, but poker is an interesting subject to work on.

Today I went through majority of the code, but it will take time to sink in.
I will work #15 "follow tie breaking rules" next,
but I don't know what I could do after that.
Maybe I will try to test showdown.

Kind Regards,

Gintautas

**Comment by rafanoronha** [comment]
@Naktibalda 

Thanks for sharing your thoughts.
Learning of Scala also motivated the start of this project.

Tie breaking rules should have a bunch of ground to be covered.
Showdown really needs some test coverage.
Have a look at TableSpec [1] regarding the setup of a showdown scenario.

In the next weeks I'm going to look for more issues around stuff needing fixes and improvements.
Please get in touch if you want talk about some aspect of the code base.

Best,

Rafael

[1] https://github.com/rafanoronha/scala-poker/blob/master/src/test/scala/spoker/TableSpec.scala#L34

**Comment by rafanoronha** [comment]
@Naktibalda  you might be interested in #39 as a way of going deeper in spoker.betting and spoker.betting.stack code base

**Pull request merged**
